name: Update Homebrew Formula

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  update-formula:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Get release information
      id: release
      uses: actions/github-script@v7
      with:
        script: |
          const release = await github.repos.getReleaseByTag({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag: context.payload.release.tag_name
          });
          return {
            release_tag: release.data.tag_name,
            assets: release.data.assets.map(asset => asset.browser_download_url)
          };

    - name: Download assets
      run: |
        mkdir -p assets
        cd assets
        for url in ${{ steps.release.outputs.assets }}; do
          curl -LO $url
        done

    - name: Extract SHA256 checksums
      id: checksums
      run: |
        cd assets
        SHA256_MAC_INTEL=$(cat lumni-x86_64-apple-darwin-${{ steps.release.outputs.release_tag }}.tar.gz.sha256)
        SHA256_MAC_ARM=$(cat lumni-aarch64-apple-darwin-${{ steps.release.outputs.release_tag }}.tar.gz.sha256)
        SHA256_LINUX_INTEL=$(cat lumni-x86_64-unknown-linux-gnu-${{ steps.release.outputs.release_tag }}.tar.gz.sha256)
        echo "::set-output name=SHA256_MAC_INTEL::${SHA256_MAC_INTEL}"
        echo "::set-output name=SHA256_MAC_ARM::${SHA256_MAC_ARM}"
        echo "::set-output name=SHA256_LINUX_INTEL::${SHA256_LINUX_INTEL}"

    - name: Checkout homebrew-lumni repository
      uses: actions/checkout@v3
      with:
        repository: serverlessnext/homebrew-lumni
        token: ${{ secrets.GITHUB_TOKEN }}
        path: homebrew-lumni

    - name: Update formula
      run: |
        cd homebrew-lumni/Formula
        cp ../templates/lumni.rb.template lumni.rb
        release_tag="${{ steps.release.outputs.release_tag }}"
        SHA256_MAC_INTEL="${{ steps.checksums.outputs.SHA256_MAC_INTEL }}"
        SHA256_MAC_ARM="${{ steps.checksums.outputs.SHA256_MAC_ARM }}"
        SHA256_LINUX_INTEL="${{ steps.checksums.outputs.SHA256_LINUX_INTEL }}"

        sed -i "s|{{ RELEASE_TAG }}|${release_tag}|g" lumni.rb
        sed -i "s|{{ SHA256_MAC_INTEL }}|${SHA256_MAC_INTEL}|g" lumni.rb
        sed -i "s|{{ SHA256_MAC_ARM }}|${SHA256_MAC_ARM}|g" lumni.rb
        sed -i "s|{{ SHA256_LINUX_INTEL }}|${SHA256_LINUX_INTEL}|g" lumni.rb

    - name: Commit and push changes
      run: |
        cd homebrew-lumni
        git config --global user.email "foo@aprxi.com"
        git config --global user.name "foo"
        git add Formula/lumni.rb
        git commit -m "Update formula to release ${release_tag}"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
